/* ===========================================================
   TEXTOS DOS MEMBROS E DA MODERAÇÃO
=========================================================== */

export const communityOperationsMessages = {
  'pt-BR': {
    membersEyebrow: 'Quem já chegou', membersTitle: 'Pessoas que escolheram aparecer', membersDescription: 'Perfis públicos aprovados, apresentados somente com a autorização de cada pessoa.', membersEmpty: 'O primeiro perfil aprovado aparecerá aqui.', memberProfile: 'Abrir perfil de {name}', adminAccess: 'Acesso interno', adminTitle: 'Moderação da comunidade', adminDescription: 'Aprove ou recuse os cadastros voluntários pendentes.', adminToken: 'Segredo de administrador', adminConnect: 'Entrar na moderação', adminPending: 'Cadastros pendentes', adminEmpty: 'Não há cadastros aguardando moderação.', adminApprove: 'Aprovar', adminReject: 'Recusar', adminExit: 'Sair', adminError: 'Não foi possível acessar a moderação. Confira o segredo e tente novamente.', adminUpdated: 'Cadastro atualizado.',
  },
  'en-US': {
    membersEyebrow: 'Who is already here', membersTitle: 'People who chose to appear', membersDescription: 'Approved public profiles, shown only with each person’s permission.', membersEmpty: 'The first approved profile will appear here.', memberProfile: 'Open {name}’s profile', adminAccess: 'Internal access', adminTitle: 'Community moderation', adminDescription: 'Approve or reject pending voluntary registrations.', adminToken: 'Administrator secret', adminConnect: 'Open moderation', adminPending: 'Pending registrations', adminEmpty: 'There are no registrations awaiting moderation.', adminApprove: 'Approve', adminReject: 'Reject', adminExit: 'Sign out', adminError: 'Moderation could not be opened. Check the secret and try again.', adminUpdated: 'Registration updated.',
  },
  'es-ES': { membersEyebrow: 'Quienes ya llegaron', membersTitle: 'Personas que eligieron aparecer', membersDescription: 'Perfiles públicos aprobados, mostrados solo con la autorización de cada persona.', membersEmpty: 'El primer perfil aprobado aparecerá aquí.', memberProfile: 'Abrir el perfil de {name}', adminAccess: 'Acceso interno' },
  'fr-FR': { membersEyebrow: 'Celles et ceux déjà présents', membersTitle: 'Les personnes qui ont choisi d’apparaître', membersDescription: 'Profils publics approuvés, affichés uniquement avec l’autorisation de chaque personne.', membersEmpty: 'Le premier profil approuvé apparaîtra ici.', memberProfile: 'Ouvrir le profil de {name}', adminAccess: 'Accès interne' },
  'de-DE': { membersEyebrow: 'Wer schon da ist', membersTitle: 'Menschen, die sichtbar sein möchten', membersDescription: 'Freigegebene öffentliche Profile, nur mit Zustimmung der jeweiligen Person.', membersEmpty: 'Das erste freigegebene Profil erscheint hier.', memberProfile: 'Profil von {name} öffnen', adminAccess: 'Interner Zugang' },
  'it-IT': { membersEyebrow: 'Chi è già qui', membersTitle: 'Persone che hanno scelto di apparire', membersDescription: 'Profili pubblici approvati, mostrati solo con il consenso di ogni persona.', membersEmpty: 'Il primo profilo approvato apparirà qui.', memberProfile: 'Apri il profilo di {name}', adminAccess: 'Accesso interno' },
  'ru-RU': { membersEyebrow: 'Кто уже здесь', membersTitle: 'Люди, решившие представиться', membersDescription: 'Одобренные публичные профили отображаются только с разрешения каждого участника.', membersEmpty: 'Здесь появится первый одобренный профиль.', memberProfile: 'Открыть профиль {name}', adminAccess: 'Внутренний доступ' },
  'ar-SA': { membersEyebrow: 'من انضم إلينا', membersTitle: 'أشخاص اختاروا الظهور', membersDescription: 'ملفات عامة تمت الموافقة عليها ولا تُعرض إلا بإذن أصحابها.', membersEmpty: 'سيظهر هنا أول ملف تتم الموافقة عليه.', memberProfile: 'فتح ملف {name}', adminAccess: 'دخول داخلي' },
  'hi-IN': { membersEyebrow: 'जो पहले से यहाँ हैं', membersTitle: 'वे लोग जिन्होंने दिखना चुना', membersDescription: 'स्वीकृत सार्वजनिक प्रोफ़ाइल, प्रत्येक व्यक्ति की अनुमति से ही दिखाई जाती हैं।', membersEmpty: 'पहली स्वीकृत प्रोफ़ाइल यहाँ दिखाई देगी।', memberProfile: '{name} की प्रोफ़ाइल खोलें', adminAccess: 'आंतरिक पहुँच' },
  'zh-CN': { membersEyebrow: '已经来到这里的人', membersTitle: '选择公开出现的人', membersDescription: '仅在本人授权后展示已审核通过的公开资料。', membersEmpty: '首个审核通过的资料会显示在这里。', memberProfile: '打开 {name} 的资料', adminAccess: '内部访问' },
  'ja-JP': { membersEyebrow: 'すでに参加している人', membersTitle: '掲載を選んだ人たち', membersDescription: '本人の許可を得て承認された公開プロフィールだけを表示します。', membersEmpty: '最初に承認されたプロフィールがここに表示されます。', memberProfile: '{name} のプロフィールを開く', adminAccess: '内部アクセス' },
  'ko-KR': { membersEyebrow: '이미 함께한 사람들', membersTitle: '공개를 선택한 사람들', membersDescription: '각 사람의 동의를 받아 승인된 공개 프로필만 표시합니다.', membersEmpty: '첫 번째 승인 프로필이 여기에 표시됩니다.', memberProfile: '{name}의 프로필 열기', adminAccess: '내부 접근' },
};
