/* ===========================================================
   AVISO DE PRIVACIDADE LOCALIZADO

   O conteúdo descreve somente os dados realmente usados pelo
   aplicativo e mantém o mesmo alcance nos 12 idiomas.
=========================================================== */

const englishSections = [
  { title: 'Data we process', text: 'The calendars work without an account. Language, theme and holiday-country preferences are stored only in your browser. If you voluntarily join the community, we receive the public name, social network, profile, interface language and country you submit.' },
  { title: 'Purposes', text: 'Preferences personalize the interface. Aggregated analytics help us understand visits and improve the project. Voluntary community data is used only to review and display an approved public profile.' },
  { title: 'Services and sharing', text: 'The site uses Cloudflare Pages, Web Analytics, Turnstile, Workers and D1, plus GitHub for source code. Telegram receives only a generic moderation alert and never the submitted name or profile. We do not sell personal data.' },
  { title: 'Retention', text: 'Pending submissions are retained for up to 60 days, rejected submissions for up to 30 days, and approved profiles until consent is withdrawn. Operational backups may remain temporarily within Cloudflare recovery windows.' },
  { title: 'Your choices and rights', text: 'You may request access, correction, unpublishing or deletion of a community profile, or withdraw consent at any time. Browser preferences can be removed by clearing this site’s local data.' },
];

export const privacyMessages = {
  'en-US': { browserTitle: '13 Calendar — Privacy', eyebrow: 'Transparency', title: 'Privacy notice', updated: 'Updated on August 24, 2026', intro: '13 Calendar is an independent educational project. This notice explains what is processed when you use the calendars, analytics and optional community form.', sections: englishSections, contactTitle: 'Contact', contactText: 'For privacy, correction or deletion requests, contact Jean Rafael Martins at', back: 'Back to the calendars', footerLink: 'Privacy notice' },
  'pt-BR': { browserTitle: '13 Calendar — Privacidade', eyebrow: 'Transparência', title: 'Aviso de privacidade', updated: 'Atualizado em 24 de agosto de 2026', intro: 'O 13 Calendar é um projeto educacional independente. Este aviso explica o que é tratado ao usar os calendários, as estatísticas e o formulário comunitário opcional.', sections: [
    { title: 'Dados tratados', text: 'Os calendários funcionam sem conta. Preferências de idioma, tema e país dos feriados ficam somente no seu navegador. Se você participar voluntariamente da comunidade, recebemos o nome público, rede social, perfil, idioma da interface e país informados.' },
    { title: 'Finalidades', text: 'As preferências personalizam a interface. Estatísticas agregadas ajudam a entender os acessos e melhorar o projeto. Os dados comunitários voluntários servem somente para revisar e exibir um perfil público aprovado.' },
    { title: 'Serviços e compartilhamento', text: 'O site usa Cloudflare Pages, Web Analytics, Turnstile, Workers e D1, além do GitHub para o código-fonte. O Telegram recebe apenas um aviso genérico de moderação, nunca o nome ou perfil enviado. Não vendemos dados pessoais.' },
    { title: 'Retenção', text: 'Pedidos pendentes são mantidos por até 60 dias, recusados por até 30 dias e perfis aprovados até a retirada do consentimento. Cópias operacionais podem permanecer temporariamente nas janelas de recuperação da Cloudflare.' },
    { title: 'Suas escolhas e direitos', text: 'Você pode pedir acesso, correção, retirada da publicação ou exclusão do perfil comunitário e retirar o consentimento a qualquer momento. As preferências do navegador podem ser apagadas ao limpar os dados locais deste site.' },
  ], contactTitle: 'Contato', contactText: 'Para pedidos de privacidade, correção ou exclusão, fale com Jean Rafael Martins em', back: 'Voltar aos calendários', footerLink: 'Aviso de privacidade' },
  'es-ES': { browserTitle: '13 Calendar — Privacidad', eyebrow: 'Transparencia', title: 'Aviso de privacidad', updated: 'Actualizado el 24 de agosto de 2026', intro: '13 Calendar es un proyecto educativo independiente. Este aviso explica el tratamiento relacionado con los calendarios, las estadísticas y el formulario comunitario opcional.', sections: [
    { title: 'Datos tratados', text: 'Los calendarios funcionan sin cuenta. Las preferencias de idioma, tema y país se guardan solo en su navegador. Si participa voluntariamente en la comunidad, recibimos el nombre público, red social, perfil, idioma y país enviados.' },
    { title: 'Finalidades', text: 'Las preferencias personalizan la interfaz. Las estadísticas agregadas ayudan a mejorar el proyecto. Los datos comunitarios se usan únicamente para revisar y mostrar un perfil público aprobado.' },
    { title: 'Servicios y comunicación', text: 'Usamos Cloudflare Pages, Web Analytics, Turnstile, Workers y D1, además de GitHub. Telegram recibe solo un aviso genérico de moderación, nunca el nombre o perfil enviado. No vendemos datos personales.' },
    { title: 'Conservación', text: 'Las solicitudes pendientes se conservan hasta 60 días, las rechazadas hasta 30 días y los perfiles aprobados hasta que se retire el consentimiento.' },
    { title: 'Sus derechos', text: 'Puede solicitar acceso, corrección, retirada o eliminación de un perfil y retirar el consentimiento en cualquier momento. Las preferencias se eliminan borrando los datos locales del sitio.' },
  ], contactTitle: 'Contacto', contactText: 'Para solicitudes de privacidad, corrección o eliminación, contacte con Jean Rafael Martins en', back: 'Volver a los calendarios', footerLink: 'Aviso de privacidad' },
  'fr-FR': { browserTitle: '13 Calendar — Confidentialité', eyebrow: 'Transparence', title: 'Avis de confidentialité', updated: 'Mis à jour le 24 août 2026', intro: '13 Calendar est un projet éducatif indépendant. Cet avis décrit les traitements liés aux calendriers, aux statistiques et au formulaire communautaire facultatif.', sections: [
    { title: 'Données traitées', text: 'Les calendriers fonctionnent sans compte. Les préférences de langue, thème et pays restent dans votre navigateur. En rejoignant volontairement la communauté, vous transmettez un nom public, un réseau social, un profil, une langue et un pays.' },
    { title: 'Finalités', text: 'Les préférences personnalisent l’interface. Les statistiques agrégées améliorent le projet. Les données communautaires servent uniquement à examiner et afficher un profil public approuvé.' },
    { title: 'Services et partage', text: 'Nous utilisons Cloudflare Pages, Web Analytics, Turnstile, Workers et D1, ainsi que GitHub. Telegram reçoit uniquement une alerte générique de modération. Nous ne vendons aucune donnée personnelle.' },
    { title: 'Conservation', text: 'Les demandes en attente sont conservées 60 jours au maximum, les refus 30 jours, et les profils approuvés jusqu’au retrait du consentement.' },
    { title: 'Vos droits', text: 'Vous pouvez demander l’accès, la correction, le retrait ou la suppression d’un profil et retirer votre consentement à tout moment.' },
  ], contactTitle: 'Contact', contactText: 'Pour toute demande de confidentialité, correction ou suppression, contactez Jean Rafael Martins à', back: 'Retour aux calendriers', footerLink: 'Confidentialité' },
  'de-DE': { browserTitle: '13 Calendar — Datenschutz', eyebrow: 'Transparenz', title: 'Datenschutzhinweis', updated: 'Aktualisiert am 24. August 2026', intro: '13 Calendar ist ein unabhängiges Bildungsprojekt. Dieser Hinweis beschreibt die Verarbeitung bei Kalendern, Statistiken und dem optionalen Gemeinschaftsformular.', sections: [
    { title: 'Verarbeitete Daten', text: 'Die Kalender funktionieren ohne Konto. Sprach-, Design- und Länderpräferenzen werden nur in Ihrem Browser gespeichert. Bei einer freiwilligen Teilnahme an der Gemeinschaft erhalten wir den öffentlichen Namen, das soziale Netzwerk, das Profil, die Sprache und das angegebene Land.' },
    { title: 'Zwecke', text: 'Präferenzen personalisieren die Oberfläche. Aggregierte Statistiken helfen, Besuche zu verstehen und das Projekt zu verbessern. Freiwillige Gemeinschaftsdaten werden nur geprüft und nach Freigabe als öffentliches Profil angezeigt.' },
    { title: 'Dienste und Weitergabe', text: 'Die Website nutzt Cloudflare Pages, Web Analytics, Turnstile, Workers und D1 sowie GitHub für den Quellcode. Telegram erhält nur einen allgemeinen Moderationshinweis, niemals den eingereichten Namen oder das Profil. Wir verkaufen keine personenbezogenen Daten.' },
    { title: 'Speicherdauer', text: 'Offene Anfragen werden bis zu 60 Tage, abgelehnte bis zu 30 Tage und freigegebene Profile bis zum Widerruf der Einwilligung gespeichert. Betriebssicherungen können vorübergehend innerhalb der Cloudflare-Wiederherstellungsfenster bestehen bleiben.' },
    { title: 'Ihre Wahl und Rechte', text: 'Sie können jederzeit Auskunft, Berichtigung, Entfernung aus der Veröffentlichung oder Löschung eines Gemeinschaftsprofils verlangen und Ihre Einwilligung widerrufen. Browserpräferenzen lassen sich durch Löschen der lokalen Website-Daten entfernen.' },
  ], contactTitle: 'Kontakt', contactText: 'Für Datenschutz-, Korrektur- oder Löschanfragen kontaktieren Sie Jean Rafael Martins unter', back: 'Zurück zu den Kalendern', footerLink: 'Datenschutz' },
  'it-IT': { browserTitle: '13 Calendar — Privacy', eyebrow: 'Trasparenza', title: 'Informativa sulla privacy', updated: 'Aggiornata il 24 agosto 2026', intro: '13 Calendar è un progetto educativo indipendente. Questa informativa descrive i dati trattati usando calendari, statistiche e modulo comunitario facoltativo.', sections: [
    { title: 'Dati trattati', text: 'I calendari funzionano senza account. Le preferenze di lingua, tema e paese restano solo nel browser. Se partecipi volontariamente alla comunità, riceviamo il nome pubblico, il social network, il profilo, la lingua e il paese indicati.' },
    { title: 'Finalità', text: 'Le preferenze personalizzano l’interfaccia. Le statistiche aggregate aiutano a capire le visite e migliorare il progetto. I dati volontari della comunità servono soltanto a revisionare e mostrare un profilo pubblico approvato.' },
    { title: 'Servizi e condivisione', text: 'Il sito usa Cloudflare Pages, Web Analytics, Turnstile, Workers e D1, oltre a GitHub per il codice sorgente. Telegram riceve solo un avviso generico di moderazione, mai il nome o il profilo inviato. Non vendiamo dati personali.' },
    { title: 'Conservazione', text: 'Le richieste in attesa sono conservate fino a 60 giorni, quelle rifiutate fino a 30 giorni e i profili approvati fino alla revoca del consenso. Copie operative possono restare temporaneamente nelle finestre di recupero di Cloudflare.' },
    { title: 'Scelte e diritti', text: 'Puoi chiedere accesso, correzione, rimozione dalla pubblicazione o cancellazione del profilo e revocare il consenso in qualsiasi momento. Le preferenze si eliminano cancellando i dati locali del sito.' },
  ], contactTitle: 'Contatti', contactText: 'Per richieste di privacy, correzione o cancellazione, contatta Jean Rafael Martins a', back: 'Torna ai calendari', footerLink: 'Informativa privacy' },
  'ru-RU': { browserTitle: '13 Calendar — Конфиденциальность', eyebrow: 'Прозрачность', title: 'Уведомление о конфиденциальности', updated: 'Обновлено 24 августа 2026 г.', intro: '13 Calendar — независимый образовательный проект. Здесь описана обработка данных календарей, статистики и необязательной формы сообщества.', sections: [
    { title: 'Какие данные обрабатываются', text: 'Календари работают без учётной записи. Настройки языка, темы и страны хранятся только в браузере. При добровольном участии в сообществе мы получаем указанные публичное имя, социальную сеть, профиль, язык и страну.' },
    { title: 'Цели', text: 'Настройки персонализируют интерфейс. Сводная статистика помогает понимать посещения и улучшать проект. Добровольные данные используются только для проверки и показа одобренного публичного профиля.' },
    { title: 'Сервисы и передача', text: 'Сайт использует Cloudflare Pages, Web Analytics, Turnstile, Workers и D1, а также GitHub для исходного кода. Telegram получает только общее уведомление о модерации, без имени и профиля. Мы не продаём персональные данные.' },
    { title: 'Срок хранения', text: 'Заявки на рассмотрении хранятся до 60 дней, отклонённые — до 30 дней, а одобренные профили — до отзыва согласия. Операционные копии могут временно сохраняться в пределах окон восстановления Cloudflare.' },
    { title: 'Ваш выбор и права', text: 'Вы можете запросить доступ, исправление, снятие с публикации или удаление профиля и в любой момент отозвать согласие. Настройки браузера удаляются при очистке локальных данных сайта.' },
  ], contactTitle: 'Контакт', contactText: 'По вопросам доступа, исправления или удаления свяжитесь с Jean Rafael Martins:', back: 'Вернуться к календарям', footerLink: 'Конфиденциальность' },
  'ar-SA': { browserTitle: '13 Calendar — الخصوصية', eyebrow: 'الشفافية', title: 'إشعار الخصوصية', updated: 'آخر تحديث: 24 أغسطس 2026', intro: '13 Calendar مشروع تعليمي مستقل. يوضح هذا الإشعار البيانات المستخدمة في التقويمات والإحصاءات ونموذج المجتمع الاختياري.', sections: [
    { title: 'البيانات التي نعالجها', text: 'تعمل التقويمات من دون حساب. تُحفظ تفضيلات اللغة والمظهر وبلد العطلات في متصفحك فقط. وعند الانضمام طوعًا إلى المجتمع نستلم الاسم العام وشبكة التواصل والملف واللغة والبلد التي ترسلها.' },
    { title: 'الأغراض', text: 'تخصص التفضيلات الواجهة، وتساعد الإحصاءات المجمعة على فهم الزيارات وتحسين المشروع. ولا تُستخدم بيانات المجتمع الطوعية إلا لمراجعة ملف عام معتمد وعرضه.' },
    { title: 'الخدمات والمشاركة', text: 'يستخدم الموقع Cloudflare Pages وWeb Analytics وTurnstile وWorkers وD1، إضافة إلى GitHub للشيفرة المصدرية. يتلقى Telegram تنبيهًا عامًا للمراجعة فقط ولا يتلقى الاسم أو الملف المرسل. نحن لا نبيع البيانات الشخصية.' },
    { title: 'مدة الاحتفاظ', text: 'تُحفظ الطلبات المعلقة حتى 60 يومًا والمرفوضة حتى 30 يومًا، وتبقى الملفات المعتمدة إلى أن تُسحب الموافقة. وقد تبقى نسخ تشغيلية مؤقتًا ضمن فترات الاستعادة لدى Cloudflare.' },
    { title: 'خياراتك وحقوقك', text: 'يمكنك طلب الوصول أو التصحيح أو إلغاء النشر أو الحذف وسحب الموافقة في أي وقت. ويمكن إزالة تفضيلات المتصفح بمسح البيانات المحلية لهذا الموقع.' },
  ], contactTitle: 'التواصل', contactText: 'لطلب الوصول أو التصحيح أو الحذف، تواصل مع Jean Rafael Martins عبر', back: 'العودة إلى التقاويم', footerLink: 'إشعار الخصوصية' },
  'hi-IN': { browserTitle: '13 Calendar — गोपनीयता', eyebrow: 'पारदर्शिता', title: 'गोपनीयता सूचना', updated: '24 अगस्त 2026 को अपडेट किया गया', intro: '13 Calendar एक स्वतंत्र शैक्षिक परियोजना है। यह सूचना कैलेंडर, आँकड़ों और वैकल्पिक समुदाय फ़ॉर्म में डेटा के उपयोग को समझाती है।', sections: [
    { title: 'हम कौन-सा डेटा संसाधित करते हैं', text: 'कैलेंडर बिना खाते के काम करते हैं। भाषा, थीम और अवकाश-देश की पसंद केवल आपके ब्राउज़र में रहती है। समुदाय में स्वेच्छा से जुड़ने पर हमें आपके द्वारा भेजा गया सार्वजनिक नाम, सोशल नेटवर्क, प्रोफ़ाइल, भाषा और देश मिलता है।' },
    { title: 'उद्देश्य', text: 'पसंद इंटरफ़ेस को अनुकूलित करती हैं। समेकित आँकड़े यात्राओं को समझने और परियोजना सुधारने में मदद करते हैं। स्वैच्छिक समुदाय डेटा केवल स्वीकृत सार्वजनिक प्रोफ़ाइल की समीक्षा और प्रदर्शन के लिए उपयोग होता है।' },
    { title: 'सेवाएँ और साझा करना', text: 'साइट Cloudflare Pages, Web Analytics, Turnstile, Workers और D1 तथा स्रोत कोड के लिए GitHub का उपयोग करती है। Telegram को केवल सामान्य मॉडरेशन सूचना मिलती है, भेजा गया नाम या प्रोफ़ाइल नहीं। हम व्यक्तिगत डेटा नहीं बेचते।' },
    { title: 'डेटा रखने की अवधि', text: 'लंबित अनुरोध अधिकतम 60 दिन, अस्वीकृत अनुरोध 30 दिन और स्वीकृत प्रोफ़ाइल सहमति वापस लेने तक रखी जाती हैं। Cloudflare की पुनर्प्राप्ति अवधि में संचालन प्रतियाँ अस्थायी रूप से रह सकती हैं।' },
    { title: 'आपकी पसंद और अधिकार', text: 'आप किसी प्रोफ़ाइल की पहुँच, सुधार, अप्रकाशन या हटाने का अनुरोध कर सकते हैं और कभी भी सहमति वापस ले सकते हैं। साइट का स्थानीय डेटा मिटाने पर ब्राउज़र की पसंद हट जाती हैं।' },
  ], contactTitle: 'संपर्क', contactText: 'पहुँच, सुधार या हटाने के अनुरोध के लिए Jean Rafael Martins से संपर्क करें:', back: 'कैलेंडर पर लौटें', footerLink: 'गोपनीयता सूचना' },
  'zh-CN': { browserTitle: '13 Calendar — 隐私', eyebrow: '透明度', title: '隐私声明', updated: '更新于 2026 年 8 月 24 日', intro: '13 Calendar 是独立教育项目。本声明说明日历、统计信息与可选社群表单所涉及的数据处理。', sections: [
    { title: '我们处理的数据', text: '日历无需账户即可使用。语言、主题和节假日国家偏好只保存在您的浏览器中。若您自愿加入社群，我们会收到您提交的公开名称、社交平台、个人资料、界面语言和国家。' },
    { title: '处理目的', text: '偏好用于个性化界面，汇总统计用于了解访问并改进项目。自愿提供的社群资料仅用于审核和展示获批的公开个人资料。' },
    { title: '服务与共享', text: '本站使用 Cloudflare Pages、Web Analytics、Turnstile、Workers 和 D1，并使用 GitHub 托管源代码。Telegram 只接收通用审核提醒，不接收提交的名称或个人资料。我们不会出售个人数据。' },
    { title: '保留期限', text: '待审核申请最多保留 60 天，被拒申请最多保留 30 天，获批资料保留至撤回同意。操作备份可能在 Cloudflare 的恢复期限内暂时保留。' },
    { title: '您的选择与权利', text: '您可以随时请求访问、更正、停止公开或删除社群资料，也可以撤回同意。清除本站的本地数据即可删除浏览器偏好。' },
  ], contactTitle: '联系', contactText: '如需访问、更正或删除数据，请联系 Jean Rafael Martins：', back: '返回日历', footerLink: '隐私声明' },
  'ja-JP': { browserTitle: '13 Calendar — プライバシー', eyebrow: '透明性', title: 'プライバシー通知', updated: '2026年8月24日更新', intro: '13 Calendar は独立した教育プロジェクトです。この通知では、カレンダー、統計、任意のコミュニティフォームで扱うデータを説明します。', sections: [
    { title: '処理するデータ', text: 'カレンダーはアカウントなしで利用できます。言語、テーマ、祝日の国の設定はブラウザー内だけに保存されます。任意でコミュニティに参加すると、送信した公開名、SNS、プロフィール、言語、国を受け取ります。' },
    { title: '利用目的', text: '設定は画面の個別化に使われ、集計統計は訪問状況の把握と改善に役立ちます。任意のコミュニティ情報は、承認された公開プロフィールの審査と表示にだけ使用します。' },
    { title: 'サービスと共有', text: 'Cloudflare Pages、Web Analytics、Turnstile、Workers、D1 と、ソースコード用の GitHub を利用します。Telegram には一般的な審査通知だけが送られ、名前やプロフィールは送られません。個人データを販売しません。' },
    { title: '保存期間', text: '審査中の申請は最大60日、却下された申請は最大30日、承認済みプロフィールは同意が撤回されるまで保存します。運用上のコピーは Cloudflare の復旧期間内に一時的に残る場合があります。' },
    { title: '選択と権利', text: 'プロフィールの開示、訂正、非公開化、削除を依頼し、いつでも同意を撤回できます。ブラウザー設定は、このサイトのローカルデータを消去すると削除されます。' },
  ], contactTitle: '連絡先', contactText: 'アクセス、訂正、削除の依頼は Jean Rafael Martins まで：', back: 'カレンダーに戻る', footerLink: 'プライバシー通知' },
  'ko-KR': { browserTitle: '13 Calendar — 개인정보', eyebrow: '투명성', title: '개인정보 안내', updated: '2026년 8월 24일 업데이트', intro: '13 Calendar는 독립 교육 프로젝트입니다. 이 안내는 달력, 통계 및 선택적 커뮤니티 양식에서 처리되는 데이터를 설명합니다.', sections: [
    { title: '처리하는 데이터', text: '달력은 계정 없이 작동합니다. 언어, 테마, 공휴일 국가 설정은 브라우저에만 저장됩니다. 자발적으로 커뮤니티에 참여하면 제출한 공개 이름, 소셜 네트워크, 프로필, 언어와 국가를 받습니다.' },
    { title: '이용 목적', text: '설정은 화면을 개인화하고, 집계 통계는 방문을 이해하고 프로젝트를 개선하는 데 사용됩니다. 자발적 커뮤니티 정보는 승인된 공개 프로필을 검토하고 표시하는 데만 사용됩니다.' },
    { title: '서비스 및 공유', text: '사이트는 Cloudflare Pages, Web Analytics, Turnstile, Workers, D1과 소스 코드용 GitHub를 사용합니다. Telegram에는 일반적인 검토 알림만 전송되며 제출한 이름이나 프로필은 전송되지 않습니다. 개인정보를 판매하지 않습니다.' },
    { title: '보유 기간', text: '대기 중인 신청은 최대 60일, 거절된 신청은 최대 30일, 승인된 프로필은 동의를 철회할 때까지 보관됩니다. 운영 사본은 Cloudflare 복구 기간 동안 일시적으로 남을 수 있습니다.' },
    { title: '선택과 권리', text: '프로필의 열람, 수정, 공개 중단 또는 삭제를 요청하고 언제든지 동의를 철회할 수 있습니다. 사이트의 로컬 데이터를 지우면 브라우저 설정도 삭제됩니다.' },
  ], contactTitle: '연락처', contactText: '열람, 수정 또는 삭제 요청은 Jean Rafael Martins에게 문의하세요:', back: '달력으로 돌아가기', footerLink: '개인정보 안내' },
};
